version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P3r1g0
      POSTGRES_DB: ambulanceAPI
    volumes:
      - ./data:/LuanaTW/Library/PostgreSQL/15/data
    ports:
      - 5432:5432
