version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      POSTGRES_USER: DB_USERNAME
      POSTGRES_PASSWORD: DB_PASSWORD
      POSTGRES_DB: ambulanceAPI
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
